### ISSUE TITLE
Improve HPC coverage & coveralls integration

### ISSUE THREAD

**Issue by adinapoli** [adinapoli/threads-supervisor#16]
cc @srijs .

We should run `stack hpc report` to identify the areas which lacks testing,
and possibly use a service like coveralls (I have tried in the past but failed miserably) to report the percentage of code coverage as a badge in the `README`.

**Comment by adinapoli** [comment]
@srijs Now we have Coveralls integration!

https://github.com/adinapoli/threads-supervisor/pull/17

We are ticking at 74%, which is not too bad, although the target is of course 100% :wink:

**Comment by srijs** [comment]
:tada:
